### ISSUE TITLE
Local Channels bad fit when create a subchannel and then select a 1 subchannel preset

### ISSUE THREAD

**Issue by jonjamcam** [Ezeer/JomTobo#12]
If you have a channel with two subchannels and then select a preset that has 1 channel this happens:

![jomtobo unfit](https://cloud.githubusercontent.com/assets/15310433/11632630/a567c338-9ce6-11e5-96a3-c2eda15fc58a.jpg)

**Comment by Ezeer** [comment]
That is normal , a Preset record is global .
Tune your tracks for something special , then record it .
It is not intented to be used for 1 track , but all the local tracks being used .

You can save a session with 1 track , 1 track+1sub , 2 tracks , etc ...
So it's to the user to organize his setups , not me .
I understand what you wanted to have ( load a preset for THiS track ) , but it's a lot of work for the dev ( me ) , as the user is free to create as many presets he wants , it is not a problem for me .
Make a preset is really quick and easy ....
Exemple : ReggaeMono,ReggaeStereo,Reggae+Drum etc ...
^^

**Comment by Ezeer** [comment]
Or fit mean position in space ? Aaah ... ok , well it's a minor bug , but a bug , yes .
lol , world best bug finder in the world Jon !

**Comment by jonjamcam** [comment]
I know "best fit" is not the "best analogy" Just didn't find another concept :D. I't only a cosmetic  issue.Not that important

**Comment by Ezeer** [comment]
yeah , but it's a bug , you do your job perfectly !
ah ah ah ...
Now try to fix it , that would help me to work on more important tasks ?
It is a problem of ui->layouts .....
edit : i resized the .exe , thx so much for that tip !

**Comment by jonjamcam** [comment]
no hurries. I'm documenting all the bugs I find.....

**Comment by jonjamcam** [comment]
Hey I updated the release info " (CC 39) "

**Comment by jonjamcam** [comment]
Ezee, now that you have static, did you test the vst build?

**Comment by Ezeer** [comment]
Nice ! Useful info , indeed .
I'm working on Pan actually , some maths ... convert a range [0,127] to [-4,4] ...
where is frank ...  ? lol

VST is a headache , because uses not mingw but msvc ...

**Comment by Ezeer** [comment]
done my math ! 
the formula i made is : 
    _//pan range is[-4,4], zero is center_
**float val=-4.0f+(value/(127/2.0f)*4.0f);**
works perfect ! 
test here ( cc10 for pan ...) :
[jomtobo.exe.txt](https://github.com/Ezeer/JomTobo/files/54403/jomtobo.exe.txt)

( i need to fix the volume fader now ... ^^ )

**Comment by jonjamcam** [comment]
Good! works perfect can you use CC 42 for pan to keep the standard?

-![](https://cloud.githubusercontent.com/assets/15310433/11606573/30353a06-9b05-11e5-833d-f173856ecf23.jpg)

**Comment by Ezeer** [comment]
lol , look at CC10 on your picture ...
i have fixed the volume also , i'm gonna release an alpha2 in the minutes that follows .

**Comment by jonjamcam** [comment]
Yes it's pan too, but it's the pan you will use for the VSTi inside the tracks, that's why there's CC42 for PAN too.....for secondary pan...unless you think the track pan is is the primary. That's our choice as devs. Many older vsti can't change the CC so ther you'l be stuck unless you have a learn funk for the track, pan etc

If we use CC 39 for volume then you have to continue with CC 42 for pan

If we use CC 7for volume then you have to continue with CC 10 for pan.

It's a mistake to mix them.

Let me put it this way. If there was no VSTi rack then I would agree with you to use 7 and 10, but because there is a rack, this choice will only confuse people who don't understand midi too much....

**Comment by jonjamcam** [comment]
TEsted alpha 2. Ezee, the volume is not reaching the maximum now, pls use the setting 105.0 for denominator

**Comment by Ezeer** [comment]
it was reaching the maximum before ?
For me not , the slider max was zero  before my fix , on my system .
Was it reaching the max for you with your keyboard ? 

i don't understand " pls use the setting 105.0 for denominator " .
where ? Why ?

For the choice of CC , that can be easily changed after , i need to follow a simple logic as starter .
Can you try to use your Vsti with MidiCC and confirm that it mooves also the fader ?
Perhaps the midi message goes directly to the vsti ? Or i could do something like that : 
if(vstiEditor->Visible==true) // send MidiCC to Vsti

**Comment by jonjamcam** [comment]
Well I don't blame you, but this is not your expertise. Now it's you who's doing what you said I should not do, but It's ok. If you forget later to change the settings I will make my own release with the correct CC, so no worries.

And Yes, the fader was working before reaching the top, but now it reaches 0 here when you use maximum value of 127.

![final automatation code_red](https://cloud.githubusercontent.com/assets/15310433/11637718/c8cb2598-9d01-11e5-8b13-a3a018b21e89.jpg)

**Comment by Ezeer** [comment]
this is what i've got when my keyboard volume is at top : 
![capture-1](https://cloud.githubusercontent.com/assets/1283808/11637691/24a30b3a-9d23-11e5-8e3f-0f0befbe8c73.jpg)

**Comment by Ezeer** [comment]
" Now it's you who's doing what you said I should not do, but It's ok. "
what are you talking about ?

**Comment by jonjamcam** [comment]
Man, you don't understand that much Midi and I do, so just use CC 39 and CC 42. That's what I 'm talking about

**Comment by Ezeer** [comment]
lol .... 
you don't answered  : " pls use the setting 105.0 for denominator "
where ?

**Comment by jonjamcam** [comment]
some quotes...

"honestly , i don't know .
Perhaps , everything is to be tried , that is new to me ..."

https://github.com/Ezeer/JomTobo/issues/9#issuecomment-162157040

"You seem like a baby that broke his toys because he don't know how to play with it ... lol 
I understand you are happy to modify the code etc ... , but your goals are unclear to me .
Here you don't make the things better , but worst"

https://github.com/Ezeer/JomTobo/issues/7#issuecomment-162441654

**Comment by Ezeer** [comment]
you don't answered  : " pls use the setting 105.0 for denominator "
where ?
If when i am at 100% with my hardware slider , and the volume fader is also at 100% ,
for me that's correct .
Now you say for you it's 50% on screen when 100% in your keyboard ....
That mean there is a serious problem of calibration somewhere , no ?
And thus we need more testers to confirm that point .

**Comment by jonjamcam** [comment]
"you don't answered : " pls use the setting 105.0 for denominator "
where ?"

https://github.com/Ezeer/JomTobo/issues/12#issuecomment-162637082

"Now you say for you it's 50% on screen when 100% in your keyboard ....
That mean there is a serious problem of calibration somewhere , no ?
And thus we need more testers to confirm that point ."

I agree.

**Comment by Ezeer** [comment]
So ... i am just trying to follow the logic .
I have modified the basetrack graduation from 120 to 127 .
And i give as parameter now the exact midi value received ( manufacturer data 0 to 127 ).
Can you try that version please ?
[jomtobo.exe.txt](https://github.com/Ezeer/JomTobo/files/54524/jomtobo.exe.txt)

the code is not pushed yet , i wait confirmation that this change fix the problem .
( now it's 1:1 , no conversion at all ... )

**Comment by jonjamcam** [comment]
now the fader is working ok in my system

**Comment by Ezeer** [comment]
great , thx for your report Jon .
I'll push then change the alpha2 with the new one .
hey ... https://www.youtube.com/watch?v=dC1yHLp9bWA
lol !

**Comment by jonjamcam** [comment]
Yea.......I remember pieces of it^^....I was probably too stoned on those years.....fun times......

**Comment by Ezeer** [comment]
alpha2 updated now .
Any idea to use MidiCC to activate solo/mute buttons ?
please ...
^^

**Comment by jonjamcam** [comment]
Buttons are controlles via Midi Note (toggle) not with CC. Use this example for guide:

http://stc.wiffbi.com/midi-implementation-chart/

**Comment by Ezeer** [comment]
Nice Jon , i'll follow that .
thx !
;)

**Comment by jonjamcam** [comment]
I have a problem, Ezee with regards to the vst plugins:

Builds work ok in my computer (i.e. they scan and recognize the vst folders), but on other laptop the vst's are empty and it will not scan any.

This is happening to me with your releases too. They don't recognize the vst folder...

problem with static?

**Comment by Ezeer** [comment]
i really don't know .
I'll look at that , i hope it is just a minor thing ...
It is in relation with the new scanner , perhaps there is a build order in subs project or something like that i missed ...
shit...

**Comment by jonjamcam** [comment]
yeah...the vstscanner is a separate process now.....

**Comment by Ezeer** [comment]
i just looked onto the .pro file of the scanner , and only msvc compiler is defined .
That could explain why it is not included in the final .exe .
The good news is that if i can fix that i'll probably be able to use the plugin too .
But i must do some tests to be sure ...

**Comment by Ezeer** [comment]
please try that , i'll explain later if that worked for you too ( minor thing ) : 
[jomtobo.exe.txt](https://github.com/Ezeer/JomTobo/files/54597/jomtobo.exe.txt)

**Comment by jonjamcam** [comment]
nop, not workig...

**Comment by Ezeer** [comment]
yeah , it is working into the release folder , but not outside .
I used a compile all option , thinking that only a part was previously built and scanner skipped ,
but now ... it turn into a major problem ...
I'll try other thing .
thx

**Comment by Ezeer** [comment]
in fact , we need to add the VstScanner.exe with the standalone now ...
Look into jamtaba2.7.0 install , you'll understand ...
^^

**Comment by jonjamcam** [comment]
I think that's not a problem.....The manual will be included too and hopefully a vst plugin, is it not?

**Comment by jonjamcam** [comment]
Another solution could be to return to the old scan process, but I think this is not a good idea. This scanner works perfectly.

**Comment by Ezeer** [comment]
yeah , now instead of a single .exe file we will release an archive containing a folder with the 2 .exe and
a doc . The plugin is an other challenge .
:)

**Comment by jonjamcam** [comment]
Ezee, I made a release based on 2.0.6 and the plugins scan ok in other computers. It's the old scan process  . Can you test pls?

[JamtabF2.exe.txt](https://github.com/Ezeer/JomTobo/files/54961/JamtabF2.exe.txt)

BTW, the new merge Elieser did changed Jamtaba to Jomtobo . The app changed (at least for me) and the git page too!

https://github.com/elieserdejesus/JamTaba/

I think this is not good.

**Comment by Ezeer** [comment]
I made the changes in Jamtaba .
Why use 2.0.6 again ? I fixed the problem , we just need to add the scanner exe in the release
and that rocks .

**Comment by jonjamcam** [comment]
Ok. It's just a choice to make. The argument is just to keep a 1 file release. Btw the old method is really unstable. It crashes a lot.

**Comment by Ezeer** [comment]
I agree , we must go ahead .
^^

i will try to implement the midiCC for mute and solo now .
Can you try with a vsti the behavior of MidiCC in jomtobo ?
Perhaps you will find some things to explore or whatever ...

**Comment by jonjamcam** [comment]
I wish I could, but with releases not compiled by me I can't use the vst ^^.

**Comment by Ezeer** [comment]
why ? what do you mean .....
Anyway , please use your dev kit to make the tests , and if you need to include the scanner , it is
located in the build folder , in his own subfolder .
That fix your problem ?

**Comment by jonjamcam** [comment]
So did you push? so I can build it myself

**Comment by jonjamcam** [comment]
ohh...you mean use my own file vstscanner.exe. Ok I'll try that

**Comment by Ezeer** [comment]
yes , or even your Qt project , i want to know how the actual ...aaah ... you don't have MidiControl branch on your local ? Yeah you can pull , every alpha is linked to the MidiControl branch sources.
^^

**Comment by jonjamcam** [comment]
ok it's scanning now.....good.

Now. It's behaving as I expected.

1.- CC7 and CC10 on CH1 control the jomtobo fader and pan respectively without the need to set an input midi...etc.....
2.- when you open a vsti (which vol control is already mapped to 7) and you set the input track to CH 1 both faders move at the same time (jomtobo an dvsti volume control)

I told you SO.

**Comment by Ezeer** [comment]
ah ah ah ... thanks for your patience   : https://www.youtube.com/watch?v=wgfu5Y64i00
i go work on buttons now .
lol

**Comment by jonjamcam** [comment]
"i go work on buttons now ."

Ok If you plan to leave it like this don't expect me to use it, man. It's just a bad design.

**Comment by Ezeer** [comment]
patience ... i am on alpha stage , remember , take it easy please .
https://www.youtube.com/watch?v=jPsnVX1HsPA

**Comment by jonjamcam** [comment]
Nah....If you really wanted to change it you've already done so. I think you like it that way....well never mind.....just let me know when you need more testing. Gtg to sleep now. cya

**Comment by Ezeer** [comment]
i am for good , with goodness .
I will not make bad choices because i am listening to wisdom .
And wisdom say there is a time for everything .
Sweet dreams Jon .
:)

**Comment by Ezeer** [comment]
Wiki updated with midi implementation chart .

**Comment by Ezeer** [comment]
**Ok If you plan to leave it like this don't expect me to use it, man. It's just a bad design.**

in the midi chart you provided to me , from Ableton Live : 

**"Customize SelectedTrackControl"**
""Tips for setting up your MIDI controller""

""All MIDI data is expected on channel 1 (or 0, depends on where your MIDI-instrument starts counting)""

So it is just your wishes that count , Jon ?
Ableton Live is a bad design too ?
^^

**Comment by Ezeer** [comment]
wiki updated with midi notes chart .

**Comment by jonjamcam** [comment]
Ezee, you can do whatever you want. This will be my last comment on the midi mapping issue, just because I'm tired to tell you you are making a big mistake and you just won't listen.

So pls, stop trying to make me look like i'm some kind of dictator, I just gave you an argument and you reply with no argument. There's a lot of possible CC to use but you still use the wrong ones for this project.

I know now that you will do a bad job with this, so I don't want to continue supporting your efforts on this matter. I'd better spend my time on productiv stuff

So I want to ask you to stop addressing to me about this topic, ok? Thx.
