### ISSUE TITLE
Add "Edit Preset" and "Delete Preset" Dialog box

### ISSUE THREAD

**Issue by jonjamcam** [Ezeer/JomTobo#4]
I was playing with the presets and we need a easy way to change the the name of the preset and to delete one preset if necessary too.

I suggest once the focus is on the preset, use right click to select delete or rename

**Comment by Ezeer** [comment]
For delete a preset , i was thinking to directly delete the file in the preset folder .
( more simple for me and easy to do for the user )
But that can be done , yeah .

Rename a preset is a lot of work for me , because a preset name is also the name of an existing
file , that mean in fact RENAME and OVERWRITE with the same data . ( or delete the file and create a new one )
mmm... could be done too.

**I suggest once the focus is on the preset, use right click to select delete or rename**
Pehaps the menu will be complicated to use , with a lot of options ( too much ? )
I will explore the possibilities i have .

thx

**Comment by jonjamcam** [comment]
no worries.....just some ideas from the dumb user's point of view. I just went click..click.....:D

**Comment by Ezeer** [comment]
But your ideas are good ....
I am actually working of it , trying to filter right/left buttons like on this thread : 
http://www.qtcentre.org/archive/index.php/t-36969.html

but that don't work .... i need to make it work ! 
lol

**Comment by Ezeer** [comment]
i made progress , i can now filter the mouse buttons per menu entry using ( as exemple here ) : 
**loadPresetsSubmenu->installEventFilter(this);// to deal with mouse buttons**

**Comment by jonjamcam** [comment]
can I test it?

**Comment by Ezeer** [comment]
you will , but that's not finished yet .
I load the presets in a listbox when you right clik on the "Load" menu option now .
I'm gonna post a picture soon , just the time to record new presets to show .
^^

**Comment by jonjamcam** [comment]
k

**Comment by Ezeer** [comment]
![capture-2](https://cloud.githubusercontent.com/assets/1283808/11461312/eedaa0da-9700-11e5-830e-8cebf9c8d919.jpg)

**Comment by jonjamcam** [comment]
looks fine. good job.

**Comment by Ezeer** [comment]
Perhaps a new menu entry would work better ?
Because it is not hidden ( users got to know the special right button trick )
But i can make both ...

files are not actually deleted , it's the configurator work i need to code now .
View ( dialog for user )<->Model (configurator Funk).....

**Comment by Ezeer** [comment]
configurator start to works  : 
( on delete )

> jt.Configurator.INFO:  Presets found :  3
> jt.Configurator.DEBUG:  Path to required preset is : "C:/Documents and Settings/Salon/Local Settings/Application Data/Jomtobo/Presets/default.json"  in  0
> jt.Configurator.INFO:  !!! Preset to delete Path is  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jomtobo/Presets/default.json"

should delete the file soon ...

**Comment by Ezeer** [comment]
Works !

console out : 

> jt.Configurator.INFO:  Presets found :  3
> jt.Configurator.DEBUG:  Path to required preset is : "C:/Documents and Settings/Salon/Local Settings/Application Data/Jomtobo/Presets/default.json"  in  0
> jt.Configurator.INFO:  !!! Preset to delete Path is  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jomtobo/Presets/default.json"
> jt.Configurator.INFO:  !!! Preset deleted ! 

i will push in the branch Jon .
To use it , you must clone the Jomtobo repository first , then checkout the configurator branch .
Ask me for help when you want to do it .

**Comment by jonjamcam** [comment]
let me see if I can remember...

jomtobo folder first.....

1.- vst sdk folder inside
2.- get the url https://github.com/Ezeer/JomTobo/Jomtobo.git
3.- console Git bash

**Comment by Ezeer** [comment]
yeah .
First right click on Jomtobo Folder and gitBash !
Once in the console , type
git clone https://github.com/Ezeer/JomTobo/Jomtobo.git

the download should start .

When done , type 
git branch

you'll see how many branches you have
Then moove to configurator by typing : 
checkout configurator
close the console

Now you put the renamed VST FOLDER

go to Jomtobo/Client , open jamtaba.pro 
etc ... 

but i've found a last minute bug , so my push will wait ...

**Comment by jonjamcam** [comment]
cloning....repository not found.......1 sec

**Comment by Ezeer** [comment]
nice .
well , i think it's a old bug so i push and will update later the fix ( the feature is more important than the bug )

**Comment by jonjamcam** [comment]
can't remember how we solved this.....should copy the chat

**Comment by Ezeer** [comment]
pushed !
^^

**Comment by jonjamcam** [comment]
![g5t c36ne fa53](https://cloud.githubusercontent.com/assets/15310433/11462102/0a99f734-96ee-11e5-8f7c-a24305b7ea19.jpg)

**Comment by jonjamcam** [comment]
Someting happened, Ezee the remove dialog do not appear anymore

**Comment by Ezeer** [comment]
oh yes ... duno why , i check that , thx
fixing ... i don't remember if that feature was working before in that branch?
I merge configurator with JonJamConcept now ... compiling
Fixed , you can pull it now ( dark css again )
